# Site settings

title: Marchronicle. # Title of your site
email: ml9723@hotmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Integrity is the essence of everything successful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marclee.xyz" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

github_username:      example  # Replace this with your GitHub username

# Build settings
markdown: kramdown
